### ISSUE TITLE
Convenience option to use renderBody by default if available

### ISSUE THREAD

**Issue by kristianmandrup** [marko-js/marko-tag-body#1]
``` html
    <ui-accordion ui="large">
      <acc-block active="true" label="Hello there" text="Page 1"></acc-block>
      <acc-block active="true" text="Page 2">
        <OMG>! I'm the body of an accordion</OMG>
      </acc-block>
    </ui-accordion>
```

The accordion `template.marko`

``` html
<div tag-body="data.body" class="ui $data.ui accordion"/>
```

Shouldn't it render the body? ie. the `acc-block`s?

`ui-accordion { ui: 'large', renderBody: [Function], invokeBody: [Function] }`

Ah, I thought by default it would `or` the expression with `renderBody` for convenience...

``` js
tagBody = require("marko-tag-body/src/tag-body-helper");

  return function render(data, out) {
    out.w('<div class="ui ' +
      escapeXmlAttr(data.ui) +
      ' accordion">');

    tagBody(out, data.body);

    out.w('</div>');
  };
```

ie. `body: bodyExpression  + ' || data.renderBody'` instead of:

``` js
        node.appendChild(compiler.createNode('tag-body', {
            body: bodyExpression || 'data.renderBody'
        }));
```

**Comment by patrick-steele-idem** [comment]
I think that would be more surprising to default to always "or in" `data.renderBody`. I think it is better to be explicit if not going with the default.

**Comment by kristianmandrup** [comment]
In my case, I always use the `or` variant, so it made sense to make a convenience helper. Thought it might be useful for others as well. That's all.
